# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0003_auto_20190328_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('1', 'Ожидает'), ('2', 'В процессе'), ('3', 'Выполнен')], default='1', max_length=1),
        ),
    ]
