# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0004_call_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('0', 'Ожидает'), ('1', 'В процессе'), ('2', 'Выполнен')], default='0', max_length=1),
        ),
    ]
