# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-30 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0006_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
