# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-30 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0007_auto_20190330_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
