# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-30 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0008_auto_20190330_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img', verbose_name='Фотография'),
        ),
    ]
