# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-31 10:32
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0009_auto_20190330_2354'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='portfolio',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
