# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-31 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0010_auto_20190331_1332'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='portfolio',
            managers=[
            ],
        ),
    ]
