# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-15 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0012_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='img', verbose_name='Фотография')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Залог')),
            ],
        ),
    ]
